### PR TITLE
fixed the readme file

### LINKED ISSUE #4: Update readme
**Is your feature request related to a problem? Please describe.**
We want to update our placeholder readme file!

**Describe the solution you'd like**
Here is what we want to add, completely replacing what we currently have

# Fortnite Api Wrapper

Fortnite api wrapper is a dart library for interacting with the [https://fortnite-api.com/](https://fortnite-api.com/).

## Installation

Use the package manager ... to install foobar.

```bash
pub get ....
```

## Usage

```dart
... TODO
```

## Contributing
Pull requests are welcome. For major changes, please open an issue first to discuss what you would like to change.

Please make sure to update tests as appropriate.

## License
[MIT](LICENSE)

**Describe alternatives you've considered**
There is no documentation usage yet, and the package is not yet published, but feel free to add in more details to it.

### PR DESCRIPTION
**Pull request by rustiever**
Fixes #4

### CODE REVIEW

**Comment by AndreVarandas** [comment]
Hi @rustiever thank you! 

Would you like to fix the issue link as with with your pull request?

[give us any feedback](https://github.com/andrevarandas/dart-fortnite-api-wrapper/issues/new)

instead of

[give us any feedback](https://github.com/dart-fortnite-api-wrapper/issues/new)

**Comment by rustiever** [comment]
> Hi @rustiever thank you!
> 
> Would you like to fix the issue link as with with your pull request?
> 
> `[give us any feedback](https://github.com/andrevarandas/dart-fortnite-api-wrapper/issues/new)`
> 
> instead of
> ` [give us any feedback](https://github.com/dart-fortnite-api-wrapper/issues/new)`

sure bro

**Comment by rustiever** [comment]
Hi @AndreVarandas 
done with the issue

**Review by AndreVarandas — APPROVED** [review]
LGTM

**Comment by AndreVarandas** [comment]
Thank you @rustiever 🚀

**Pull request merged**
